# Generated by Django 4.2.5 on 2023-10-02 10:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="author",
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("#FF5733", "Red"),
                    ("#33FF57", "Green"),
                    ("#3366FF", "Blue"),
                    ("#FFFF33", "Yellow"),
                    ("#FF33FF", "Purple"),
                    ("#FFA07A", "Light Salmon"),
                    ("#32CD32", "Lime Green"),
                    ("#1E90FF", "Dodger Blue"),
                    ("#FFD700", "Gold"),
                    ("#9932CC", "Dark Orchid"),
                    ("#20B2AA", "Light Sea Green"),
                    ("#FF69B4", "Hot Pink"),
                    ("#7B68EE", "Medium Slate Blue"),
                    ("#00FF7F", "Spring Green"),
                    ("#FF4500", "Orange Red"),
                    ("#8A2BE2", "Blue Violet"),
                    ("#ADFF2F", "Green Yellow"),
                    ("#00CED1", "Dark Turquoise"),
                    ("#FF6347", "Tomato"),
                ],
                default=1,
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="🏠", max_length=2),
        ),
        migrations.AddField(
            model_name="transaction",
            name="period_of_recurrence",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurrence",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999999.99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("expense", "Expense"), ("income", "Income")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_app.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999.99),
                        ],
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("rolling", "Rolling"), ("fixed", "Fixed")],
                        max_length=10,
                    ),
                ),
                ("period", models.PositiveIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_app.category",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_app.subcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="🏠", max_length=2)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF5733", "Red"),
                            ("#33FF57", "Green"),
                            ("#3366FF", "Blue"),
                            ("#FFFF33", "Yellow"),
                            ("#FF33FF", "Purple"),
                            ("#FFA07A", "Light Salmon"),
                            ("#32CD32", "Lime Green"),
                            ("#1E90FF", "Dodger Blue"),
                            ("#FFD700", "Gold"),
                            ("#9932CC", "Dark Orchid"),
                            ("#20B2AA", "Light Sea Green"),
                            ("#FF69B4", "Hot Pink"),
                            ("#7B68EE", "Medium Slate Blue"),
                            ("#00FF7F", "Spring Green"),
                            ("#FF4500", "Orange Red"),
                            ("#8A2BE2", "Blue Violet"),
                            ("#ADFF2F", "Green Yellow"),
                            ("#00CED1", "Dark Turquoise"),
                            ("#FF6347", "Tomato"),
                        ],
                        default=1,
                        max_length=7,
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="circle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget_app.circle",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget_app.subcategory",
            ),
        ),
    ]
