# Generated by Django 4.2.5 on 2023-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "budget_app",
            "0002_remove_category_author_category_color_category_icon_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
