# Generated by Django 4.2.5 on 2023-10-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_app", "0003_alter_transaction_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
