# Generated by Django 4.2.5 on 2023-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_app", "0004_alter_transaction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
