# Generated by Django 4.2.5 on 2023-10-03 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_app", "0006_remove_transaction_period_of_recurrence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
        migrations.AddField(
            model_name="transaction",
            name="date_of_transaction",
            field=models.DateField(default=datetime.date(2023, 10, 3)),
        ),
        migrations.AddField(
            model_name="transaction",
            name="date_of_update",
            field=models.DateField(default=datetime.date(2023, 10, 3)),
        ),
    ]
