# Generated by Django 4.2.5 on 2023-10-03 08:47

import budget_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_app", "0007_remove_transaction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date_of_transaction",
            field=models.DateField(default=budget_app.models.get_current_date),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date_of_update",
            field=models.DateField(default=budget_app.models.get_current_date),
        ),
    ]
