# Generated by Django 4.2.5 on 2023-10-03 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_app", "0008_alter_transaction_date_of_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="interval_of_recurrence",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("expense", "Expense"), ("income", "Income")],
                default="expense",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="units_of_recurrence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("days", "Days"),
                    ("weeks", "Weeks"),
                    ("months", "Months"),
                    ("years", "Years"),
                ],
                default="months",
                max_length=7,
                null=True,
            ),
        ),
    ]
